name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install gtest
      run: brew install googletest
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: test
      run: make test
